### ISSUE TITLE
Faltam 4 coisas pra rodar o fact!!

### ISSUE THREAD

**Issue by rmparanhos** [wallacebaleroni/Ruby-on-IMP#15]
- [x] 4) Chamar função do SO, no caso print
- [x] 3) Evaluar blocos de comandos
- [x] 1) Diferenciar CI de EV (plotkin)
- [x] 2) Guardar a pilha q precede o loop para ela ser executada novamente

**Comment by rmparanhos** [comment]
Pilha auxiliar para o controle pode ajudar nas duas primeiras

**Comment by rmparanhos** [comment]
Uma variavel q salve a ultima operaco lida da pilha de controle pode ajudar na primeira.

**Comment by rmparanhos** [comment]
4 coisas na real

**Comment by rmparanhos** [comment]
O problema da terceira deve ser no transform

**Comment by wallacebaleroni** [comment]
Tudo feito
