### ISSUE TITLE
Parser nao aceita calls com mais de um argumento

### ISSUE THREAD

**Issue by rmparanhos** [wallacebaleroni/Ruby-on-IMP#35]
Failed to match sequence (MODULE_OP IDENT CLAUSES END_OP) at line 13 char 3. `- Failed to match sequence ('end' BLANK?) at line 13 char 3.    `- Expected "end", but got "fac" at line 13 char 3.

**Comment by wallacebaleroni** [comment]
Fiz uma mudança super incrível e difícil de fazer e deu certo
